# Generated by Django 4.0 on 2022-01-07 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_supportpannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=datetime.date, max_length=15),
            preserve_default=False,
        ),
    ]
