# Generated by Django 4.0 on 2022-01-07 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
